#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const SRC_DIR = path.join(ROOT, 'src');
const HEADER = "// generated by 'npm run generate:index'\n\n";

const isExportableTsFile = (name) =>
    name.endsWith('.ts') &&
    name !== 'index.ts' &&
    !name.endsWith('.bak');

const writeBarrel = (filePath, exportPaths) => {
    const lines = exportPaths.map((p) => `export * from '${p}';`);
    const content = HEADER + lines.join('\n') + (lines.length ? '\n' : '');
    fs.writeFileSync(filePath, content);
};

const generateForDirectory = (dirPath) => {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });

    const files = entries
        .filter((entry) => entry.isFile() && isExportableTsFile(entry.name))
        .map((entry) => `./${entry.name.slice(0, -3)}`)
        .sort((a, b) => a.localeCompare(b));

    const directories = entries
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .sort((a, b) => a.localeCompare(b));

    const dirExports = [];
    for (const name of directories) {
        const childDir = path.join(dirPath, name);
        const childHasExports = generateForDirectory(childDir);
        if (childHasExports) {
            dirExports.push(`./${name}`);
        }
    }

    const exportsToWrite = [...dirExports, ...files];
    writeBarrel(path.join(dirPath, 'index.ts'), exportsToWrite);
    return exportsToWrite.length > 0;
};

writeBarrel(path.join(ROOT, 'index.ts'), ['./src']);
generateForDirectory(SRC_DIR);

